### PR TITLE
Calendar

### PR DESCRIPTION
**Pull request by jiyoon-wd**
Calender info fetch - need to double check if calendar event api requires permissions
currently, api seems to be connected but empty array is getting returned. 
My calendar is empty on my canvas, so I was not sure.

### CODE REVIEW

**Comment by rahulon12** [comment]
Could you try using the calendar attached to each course object instead? That might work better, and you can just add a tab in each course view along with all the others, like files and assignments

**Comment by azooz2003-bit** [comment]
@jiyoon-wd Just tried pulling, I don't see the calendar tab. Am I missing something?

**Comment by jiyoon-wd** [comment]
Really? maybe it's because I accidentally committed without the project.pbxproj file, which Rahul added later. Please let me know if you still can't see it @azooz2003-bit

**Comment by rahulon12** [comment]
> Really? maybe it's because I accidentally committed without the project.pbxproj file, which Rahul added later. Please let me know if you still can't see it @azooz2003-bit

@jiyoon-wd where did you add the calendar tab? At least in the changes it seems like you added the Calendar view but there's no way in the app to actually access it.

**Comment by jiyoon-wd** [comment]
Oh since I didn't want to mess up other views, I manually changed the App file to run it individually. My bad
Also, this is my attempt with ics on course object but It gave me this error. 
Screenshot 2024-09-16 at 9 15 11 PM

**Comment by azooz2003-bit** [comment]
@jiyoon-wd There shouldn't be an `AttributedText` file in the PR.

**Comment by azooz2003-bit** [comment]
> @jiyoon-wd There shouldn't be an `AttributedText` file in the diff.

@rahulon12 WDYT.

**Review by azooz2003-bit — APPROVED** [review]

**Comment by rahulon12** [comment]
> > @jiyoon-wd There shouldn't be an `AttributedText` file in the diff.
> 
> @rahulon12 WDYT.

Yeah, @jiyoon-wd it looks like you did a merge and pull instead of a rebase. At this point it might be easier to create another branch and move over your changes.

**Comment by jiyoon-wd** [comment]
I see, just made a new branch calendar-ics!

**Comment by rahulon12** [comment]
New PR #15

**Pull request closed without merging**
