### PR TITLE
add function to call api and get enrollment with courseID

### PR DESCRIPTION
**Pull request by mko02**
The callAPi function is just a is a general API call in swift, so we don't have to keep writing the same thing

### CODE REVIEW

**Review by rahulon12 — CHANGES_REQUESTED** [review]
@azooz2003-bit made a few changes in #6, which you might wanna rebase from instead 🙃

**Comment by azooz2003-bit** [comment]
> @azooz2003-bit made a few changes in #6, which you might wanna rebase from instead 🙃
> 
> edit: nvm, I didn't realize this was just in order to add the callAPI function. I'm guessing since we have Aziz's new changes, we don't need this?

Yeah, this looks great! But we already have a handler for that under `Services` folder. We don't need this anymore.

**Comment by azooz2003-bit** [comment]
PS, `main` already has a `.gitignore`

**Review by azooz2003-bit — COMMENTED** [review]
Comments above.

**Pull request closed without merging**
