### PR TITLE
People view

### PR DESCRIPTION
**Pull request by mko02**
unstage DEVELOPMENT_TEAM value, there was another one i forgot to change

### CODE REVIEW

**Comment by rahulon12** [comment]
I'm confused, didn't we merge this with #30 ?

**Comment by mko02** [comment]
> I'm confused, didn't we merge this with #30 ?

There was 2 DEVELOPMENT_TEAM values, one in /* Debug */ and one in /* Release */
I thought there was only one, and only changed the value in debug.

**Comment by rahulon12** [comment]
Ah, that's fine. I'll put up a PR to remove those values entirely. We can close this.

**Comment by mko02** [comment]
sounds good!

**Pull request closed without merging**
