### PR TITLE
WIP Pagination

### PR DESCRIPTION
**Pull request by iWatger**
Pagination has been implemented, but it blocks until all data is received, so it doesn't provide the best experience, so maybe altering fetch batch to return some data, and a link to the next URL would work better.

### CODE REVIEW

**Review by rahulon12 — COMMENTED** [review]
Can we pull the next batch when we scroll to the bottom of the list?

**Comment by rahulon12** [comment]
> Can we pull the next batch when we scroll to the bottom of the list?

I think you can use this: https://developer.apple.com/documentation/swiftui/view/scrollposition(id:anchor:)

**Review by rahulon12 — APPROVED** [review]
The code looks good to me. We need to cache the list of people if we want people backtrack to work efficiently. Let's have @azooz2003-bit look at it too.

Could we have a loading icon on the people page and/or the batches load in immediately instead of waiting for all batches?

**Review by azooz2003-bit — CHANGES_REQUESTED** [review]

**Comment by iWatger** [comment]
closing to use with Aziz's branch instead

**Pull request closed without merging**
